### ISSUE TITLE
Character count range slider issues

### ISSUE THREAD

**Issue by epsilon42** [timbowhite/tld-list-tracker#11]
I've noticed a few issues with the character count range slider:

1. Doesn't allow setting a number between 2 and 5 as the top handle seems to just snap to 2 when it gets close.
![image](https://github.com/timbowhite/tld-list-tracker/assets/22780359/7055a43b-4b82-4e4c-9f36-6a3465393c08)

2. If you have the range slider set to say (low: 5, high: 24), and then try to click and drag the top handle it has unexpected behaviour where the lower handle seems to change value instead of the top handle.

**Comment by timbowhite** [comment]
Thanks - I plan on replacing the existing slider js library this week, possibly with this one:

https://github.com/mzusin/toolcool-range-slider

Feel free to suggest other FOSS sliders.

**Comment by epsilon42** [comment]
No preference, that one looks good! Just want to be able to filter shorter domain extensions again :)

Great site by the way thanks making this tool available.

**Comment by timbowhite** [comment]
Appreciate it!

The slider filter lib has been updated, should be a big improvement:

[https://tld-list.com/](https://tld-list.com/)
