### ISSUE TITLE
Spaceship, free whois privacy .foo tld

### ISSUE THREAD

**Issue by federdaemn** [timbowhite/tld-list-tracker#12]
Hello,

[Spaceship](https://www.spaceship.com/) has free whois privacy forever, but the [.foo tld-list page](https://tld-list.com/tld/foo) says it's unsupported.

Thanks for this great service without alternatives!
federdaemn

**Comment by timbowhite** [comment]
Thanks for the heads up. You're right, will work on getting this corrected soon.

![.foo](https://i.imgur.com/o7mQsTN.png)

**Comment by timbowhite** [comment]
OK this data point has been corrected:


![.foo](https://i.imgur.com/9JoZUSj.png)

**Comment by federdaemn** [comment]
Looks good for me! 👍
